---
abstract: 'Booking.com CPAN authors'
author:
  - 'Abigail <cpan@abigail.be>'
build_requires:
  Acme::CPANAuthors: 0
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
configure_requires:
  Acme::CPANAuthors: 0
  ExtUtils::MakeMaker: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
keywords: []
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Booking
no_index:
  directory:
    - t
    - inc
requires:
  Acme::CPANAuthors::Register: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  repository: git://github.com/Abigail/Acme--CPANAuthors--Booking.git
version: 2012052501
x_test_requires:
  Acme::CPANAuthors: 0
  Test::More: 0.88
  strict: 0
  warnings: 0
